### ISSUE TITLE
Pause an Play

### ISSUE THREAD

**Issue by liyuhack** [gtreshchev/AudioAnalysisTools#10]
Sorry for disturbing. Epic store is not suitable to communicate. So i come here.

Thanks for the fast replay. I created audio component in my actor and set it to wave sound. But but i can't connect to your audio analaysis BPs. Caue object reference is not the same. Please can you describe brefily. Here is my blueprint implmentation screenshot. 

![Screenshot (13)](https://user-images.githubusercontent.com/53454723/208232811-251b9e82-5223-4570-b3a0-92230243d8fd.png)

**Comment by gtreshchev** [comment]
Hi, it feels like you're a bit confused about the nodes. Here is the proper BP implementation that seems to be assumed for your case.
![image](https://user-images.githubusercontent.com/69837452/208238312-7ab95ca0-e7c6-4d1d-8305-a2da3972e019.png)

**Comment by liyuhack** [comment]
> Hi, it feels like you're a bit confused about the nodes. Here is the proper BP implementation that seems to be assumed for your case. ![image](https://user-images.githubusercontent.com/69837452/208238312-7ab95ca0-e7c6-4d1d-8305-a2da3972e019.png)

Tnx very much. It worked
