### ISSUE TITLE
Detect Build up

### ISSUE THREAD

**Issue by liyuhack** [gtreshchev/AudioAnalysisTools#12]
Hay bro..... this isn't actually an issue but, is there any way to detect building up of high beat in music using your plugin. I tried to figure out how for 3 days but no luck. Also ur plugin can return whether or not the audio is beating for the specified time(beat detection). how to get that beat frequency in addition to the bool return at that time. 

Thanks very much for this free plugin 🙏

**Comment by gtreshchev** [comment]
Hi. Thank you for your pleasant words :)

You can specify the range for beat detection manually (see `IsBeatRange` whose range is taken from the FFT sub-bands size), and if you want more accuracy you can specify your own FFT sub-bands size (see `UpdateFFTSubbandsSize` in the beat detection object).

**Comment by liyuhack** [comment]
> Hi. Thank you for your pleasant words :)
> 
> You can specify the range for beat detection manually (see `IsBeatRange` whose range is taken from the FFT sub-bands size), and if you want more accuracy you can specify your own FFT sub-bands size (see `UpdateFFTSubbandsSize` in the beat detection object).

ok thanks bro..... i will try it to implment in this way to get frequency of specific band...... but how to detect it is building the beat(the part before the beating start). I mean detecting sound flow in a clip drops in/out. sorry for my bad english.

**Comment by gtreshchev** [comment]
The algorithm doesn't detect the start/end beat of a particular frame, but whether they occur at a particular time. Since the beats happen very fast and the algorithm accuracy is not so great (which is compensated by the high processing speed), it is not so easy to distinguish between the beginning and the end of a beat. 

So that the algorithm is okay in terms of actually determining when a beat happened, but without taking into account start or end states of a particular beat.

**Comment by liyuhack** [comment]
> The algorithm doesn't detect the start/end beat of a particular frame, but whether they occur at a particular time. Since the beats happen very fast and the algorithm accuracy is not so great (which is compensated by the high processing speed), it is not so easy to distinguish between the beginning and the end of a beat.
> 
> So that the algorithm is okay in terms of actually determining when a beat happened, but without taking into account start or end states of a particular beat.

ok thanks very much for your help.  🙏 🙏🙏🙏🙏
