### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by EiZi233** [gtreshchev/AudioAnalysisTools#2]
I am kind of new to unreal, and I tried to follow the document and is confused. In the second step of "How to use the plugin" section, it told us to bind to "On Generate PCM data", there there's no such thing in my editor. A lot of funtions seems to be missing, not pretty sure something went wrong like I am using the wrong version of Unreal or the document is not updated so the name is wrong?

**Comment by gtreshchev** [comment]
Are you using the GitHub or Marketplace version? GitHub has the latest version, but Marketplace hasn't been updated yet. Update on Marketplace with latest changes coming soon.

If you are using the GitHub version, then before deploying the AudioAnalysisTools plugin, you also need to deploy the RuntimeAudioImporter, as the plugin depends on it.

**Comment by cjlovelace** [comment]
Hello there! I'm having this same issue. I've downloaded both RuntimeAudioImporter and AudioAnalysisTools from GitHub. Both are properly deployed, but OnGeneratePCMData is missing in my editor as well.

**Comment by gtreshchev** [comment]
@cjlovelace Once the sound wave is imported, you will be able to bind to this delegate from the imported sound wave. 
![image](https://user-images.githubusercontent.com/69837452/154258942-5f988ec3-6676-48ba-bbd1-9a4c46fcb30f.png)
This delegate can only be bound from an Imported Sound Wave object.

**Comment by gtreshchev** [comment]
Here is the detailed information on how to use the plugin: https://github.com/gtreshchev/AudioAnalysisTools/wiki/How-to-use-the-plugin
