### ISSUE TITLE
FFTSubbandsSize cannot be set higher than 512 or beat detection fails

### ISSUE THREAD

**Issue by Caffiendish** [gtreshchev/AudioAnalysisTools#5]
If FFTSubbandsSize is set higher than 512, beat detection fails every frame.

**Comment by gtreshchev** [comment]
This is because of the buffer size you are probably getting from OnGeneratePCMData. I assume you have two channels (so the PCM data size is 1024 each generation), and therefore your sample size is 512.

**Comment by Caffiendish** [comment]
So, the FFTSubbandSize shouldn't allow being set higher than the possible sample size, or should set itself accordingly upon receiving the first frame where it's set higher than could be useful?

**Comment by gtreshchev** [comment]
First is right, the FFTSubbandSize shouldn't allow being set higher than the possible sample size.
The second one may also be true, but this does not follow directly from the algorithm, so need to test this approach to be sure.
