### ISSUE TITLE
FFT Alloc typo?

### ISSUE THREAD

**Issue by Caffiendish** [gtreshchev/AudioAnalysisTools#7]
Is the second `FFTStateStruct` not supposed to be `FFTComplexSamples` at
https://github.com/gtreshchev/AudioAnalysisTools/blob/main/Source/AudioAnalysisTools/Private/Analyzers/FFTAnalyzer.cpp#L379 ?

Judging from https://github.com/mborgerding/kissfft/blob/master/kiss_fft.c#L342 at least.

**Comment by gtreshchev** [comment]
Yes, this is a bug. Thanks for letting me know!
